first try to run tests
mariodavid/cuba-petclinic-heroku pull request #1
Opened 2020-04-07 18:37 UTC by mariodavid

2020-04-08 14:08 UTC, alexbudarov requested changes

2020-04-08 14:08 UTC, alexbudarov commented on modules/core/test/com/haulmont/sample/petclinic/test-app.properties
> +cuba.dataSource.dbName=petclinic-heroku
For test-runtime the only necessary properties are: url, username and password. 

host, port, connectionParams - necessary only to create new database (to run CREATE DATABASE). So no sense to put them to test-app.properties.

2020-04-08 14:11 UTC, alexbudarov commented on modules/core/test/com/haulmont/sample/petclinic/test-app.properties
> +cuba.dataSource.dbName=petclinic-heroku
proof here: com.haulmont.cuba.core.sys.DataSourceProvider#getApplicationConnection

2020-04-08 14:12 UTC, alexbudarov commented on .github/workflows/integration-test.yml
> +          JDBC_DATABASE_URL: jdbc:postgresql://localhost:${{ job.services.postgres.ports[5432] }}/petclinic-heroku?user=postgres&password=postgres
Aren't username and password on the end of JDBC_DATABASE_URL superficial?
Or it is requirement of heroku.

2020-04-08 14:34 UTC, mariodavid commented on .github/workflows/integration-test.yml
> +          JDBC_DATABASE_URL: jdbc:postgresql://localhost:${{ job.services.postgres.ports[5432] }}/petclinic-heroku?user=postgres&password=postgres
heroku passes in this particular ENV variable, which contains the information like this:

```
[cuba-petclinic-heroku] heroku run env | grep JDBC_DATABASE_URL
JDBC_DATABASE_URL=jdbc:postgresql://ec2-54-247-xxx-xxx.eu-west-1.compute.amazonaws.com:5432/dcbgxxxxxx?user=ullmqsuijxdanjxxxxxxxxxxxx&password=1aacb8d4d1b2d93e34c0de9638618c371e43ed06824f2xxxxxxxxxxxx&sslmode=require
```

As this string was the only one needed, at least for production it makes sense to use that instead of having to pass in all the three values. For just CI testing, it might not be necessary. Or what do you in particular mean by superficial?

2020-04-08 14:34 UTC, mariodavid commented on modules/core/test/com/haulmont/sample/petclinic/test-app.properties
> +cuba.dataSource.dbName=petclinic-heroku
ok i see. Reason why I in the first place put it in, was that I was hoping I could use this file also as a spring profile definition in the test root. This way I would not be forced to put another `integrationtest-app.properties` or something into src directory, so that I can keep it together somehow for the `createDb` gradle task. 

But I think this is not possible? In this case it can probably go away from here...

2020-04-08 14:50 UTC, alexbudarov commented on modules/core/test/com/haulmont/sample/petclinic/test-app.properties
> +cuba.dataSource.dbName=petclinic-heroku
Also:

1) cuba.dataSource.jdbcUrl property referencing JDBC_DATABASE_URL - is not necessary.
For GitHub CI - you set up these properties in integrationtest-app.properties
For local test run from IDEA this system property can't be resolved and it makes tests to fail with error.

2) 
cuba.dataSource.username and cuba.dataSource.password are also not necessary here.
"Default" project values are set in app.properties.

cuba.dataSource.dbName
TO BE DISCUSSED
Local tests from IDEA usually use the same database, right?
If we want database for local IDEA tests to be different, we will have to create another CubaDbCreation task in the build.gradle, e.g. "createTestDb".

2020-04-08 18:06 UTC, mariodavid commented on modules/core/test/com/haulmont/sample/petclinic/test-app.properties
> +cuba.dataSource.dbName=petclinic-heroku
> cuba.dataSource.jdbcUrl property referencing JDBC_DATABASE_URL - is not necessary.

I know what you mean, but I would like to avoid that solution. I know I could hard-code the credential values in the `integrationtest-app.properties` and mirror those values in the Github CI configuration. 

But from my understanding, those are two different things that should be kept away from each other. The first thing is that it is oftentimes a little hard to understand that connection in different files, when "you know you have to change something here and there" in order to make it work. But this is more a minor thing.
The second and more important part is, that the application binary itself should not contain environment/context information if it is avoidable. 

For credentials, you would like to keep that outside of source control. To be fair, this is not actually true here, because the alternative would be we put the same credential values in the CI yml file. But at least they belong together in this "CI program definition" and are not also in the application itself.

But if you think about the port, this is a very good example, where you simply cannot hard-code in the properties file. The reason is the same: it is environment-specific. In this case, it is even so dynamic, that it has to be evaluated at execution time of the build.

When it comes to "promoting best practices" from everything that I saw over the years when it comes to CI/CD is: environment variables are king in the container/cloud world, because they are so universal. This means that every CI system has native support for them in the configuration parts. Also, the runtimes support them out of the box (see Heroku, but also Docker, Kubernetes, Elastic Beanstalk, AWS Lamda, etc.).
So from my taste, it is reasonable to use this building block for passing in variable data.

Keeping the line in the context config file:

```properties
cuba.dataSource.jdbcUrl = ${JDBC_DATABASE_URL}
```
is a valid trade-off. On the one side, I like the explicitness of it, that you basically define: For this context: `integrationtest` the jdbcUrl is fetched from this ENV variable next to something that should be kept in this config file like `cuba.automaticDatabaseUpdate = true` seems a good compromise.

On the other hand, I also like the approach of "only controlling it from the outside" as I did it for the Spring profile selection here: https://github.com/mariodavid/cuba-petclinic-heroku/pull/1/files#diff-602983717d0a82cc8fc4cb08fe0b53cbR41

There only the ENV variable (and with that basically the user/caller) defines this variable and the framework just picks it up. TBH I was expecting that the whole ENV var interpretation from CUBA 7.2 works like this.

In Spring Boot it works just like that:
If you have a config property called `app.myConfig.value` you can either do the following:
1. set the value in the application.properties file: `app.myConfig.value = myFileValue`
2. pass the value in as Java System parameter: `java -jar -Dapp.myConfig.value=myParameterValue app.jar`
3. set the OS environment variable: `export APP_MYCONFIG_VALUE=myEnvValue`

All those options have the same effect: The app starts with the value in. So in app code:

```
@Component
class MyClass {

  @Value("{app.myConfig.value}")
  String myConfigValue
}
```
will have the value assigned in all three cases.

For CUBAs implementation it does not seem to be like that. Instead the ENV vars are "just" passed into the `app.properties` for interpolation. This is the reason I added the line there:
`cuba.dataSource.jdbcUrl = ${JDBC_DATABASE_URL}` - because I learned that I have to do it. Perhaps this is actually a misunderstanding, but at least from the tests I concluded that behavior: https://github.com/cuba-platform/cuba/blob/master/modules/core/test/spec/cuba/core/properties/EnvPropertiesTest.groovy. If CUBA actually works like SB in this case, then probably it makes sense to leverage that capability here as well and get rid of the line completely. 

The only downside for the Heroku case is that for SB Heroku creates dedicated ENV variable `SPRING_DATASOURCE_URL` which contains the same value, but this way SB automatically picks up the connection string without having to configure anything at all (because of the above-described transformation to `spring.dataSource.url`).

2020-04-08 18:08 UTC, mariodavid commented on modules/core/test/com/haulmont/sample/petclinic/test-app.properties
> +cuba.dataSource.dbName=petclinic-heroku
> Local tests from IDEA usually use the same database, right?
> If we want database for local IDEA tests to be different, we will have to create another 
 CubaDbCreation task in the build.gradle, e.g. "createTestDb".

Perhaps it would be really a good idea to promote that split. I mean practically running that on the CI server it will be a different DB instance anyways since it is a different server. But to avoid the clash on the local system I think it would make sense to make that split the default behavior (even if we have a little bit more verbose solution).

Can you elaborate what to do here in particular?

2020-04-09 13:56 UTC, alexbudarov commented on modules/core/test/com/haulmont/sample/petclinic/test-app.properties
> +cuba.dataSource.dbName=petclinic-heroku
OK, I completely agree with everything about environment variables and avoiding duplication of properties. Let's supply all we can with environment variables and avoid hard-coding username and password.

But every variable should know its place.
Things related to GitHub tests - should be in the integrationtest-app.properties.
Everything related to all tests (local tests and CI tests) - should be in test-app.properties.

So if you put:
> cuba.dataSource.jdbcUrl = ${JDBC_DATABASE_URL}

to __test-app.properties__
and try to launch tests locally from IDEA - they will fail, because your work environment doesn't supply this environment variable.

I was talking about that.

2020-04-09 14:03 UTC, alexbudarov commented on modules/core/test/com/haulmont/sample/petclinic/test-app.properties
> +cuba.dataSource.dbName=petclinic-heroku
> Perhaps it would be really a good idea to promote that split. I mean practically running that on the CI server it will be a different DB instance anyways since it is a different server. But to avoid the clash on the local system I think it would make sense to make that split the default behavior (even if we have a little bit more verbose solution).
> 
> Can you elaborate what to do here in particular?

I was thinking that we could give an idea to users in the guide.
That if someone wants to run tests locally on a separate database, he needs to make few simple things.
1) create separate task in build.gradle
2) run this task manually when necessary (before tests, after db schema changed)
3) modify test-app.properties, changing cuba.dataSource.dbName

That's it.

2020-04-09 14:06 UTC, alexbudarov commented on .github/workflows/integration-test.yml
> +          JDBC_DATABASE_URL: jdbc:postgresql://localhost:${{ job.services.postgres.ports[5432] }}/petclinic-heroku?user=postgres&password=postgres
Ah, probably I get it.
Heroku provides JDBC_DATABASE_URL but we cannot use this variable in the "gw createDb" and "gw test".
So you had to construct JDBC_DATABASE_URL from scratch and set fixed username and password.

2020-04-11 13:15 UTC, mariodavid commented on .github/workflows/integration-test.yml
> +          JDBC_DATABASE_URL: jdbc:postgresql://localhost:${{ job.services.postgres.ports[5432] }}/petclinic-heroku?user=postgres&password=postgres
yes, I think you are right. If we are strictly talking about CI - then it is not necessary. That being said, I have cleaned up the majority of the mess. Perhaps you take another look.

In this repository, I will keep the balance between what is easy to understand when also working with Heroku (keep the mental model the same between CI and staging / prod) and the perfect CI system.

When we shift gears and take this is a basis for a guide - let's reiterate and cut out all stuff that mainly makes sense because of Heroku.

2020-04-11 13:16 UTC, mariodavid commented
For now, I created a working solution. The bespoken remaining problems I will create in another PR which will then have the "more correct" version and we can just wait until the next CUBA release to see that it works with this CI setting then as well.

2020-04-11 13:26 UTC, merged